apiVersion: v1
kind: Namespace
metadata:
  name: api-patient

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-patient-deployment
  namespace: api-patient
  labels:
    app: api-patient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-patient
  template:
    metadata:
      labels:
        app: api-patient
    spec:
      containers:
      - name: api-patient
        image: lucaslearningsw/hack-api-patient:latest
        ports:
        - containerPort: 8084
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: MSSQL_USER
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: MSSQL_USER
        - name: SA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: SA_PASSWORD
        - name: MSSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: MSSQL_HOST
        - name: JWT_ISSUER
          valueFrom:
            configMapKeyRef:
              name: jwt-config
              key: JWT_ISSUER
        - name: JWT_AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: jwt-config
              key: JWT_AUDIENCE
        - name: JWT_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: jwt-config
              key: JWT_SECRET_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: api-patient-service
  namespace: api-patient
spec:
  selector:
    app: api-patient
  ports:
    - protocol: TCP
      port: 8082      # Port exposed externally
      targetPort: 8084 # Port on the container
  type: NodePort