# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Develop

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore Hackathon.HealthMed.sln
      
    - name: Build
      run: dotnet build Hackathon.HealthMed.sln --no-restore
      
    - name: Test
      run: dotnet test Hackathon.HealthMed.sln --no-build --verbosity normal
