apiVersion: v1
kind: Namespace
metadata:
  name: sqlserver-namespace

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
  namespace: sqlserver-namespace
  labels:
    app: sqlserver
  annotations:
    description: "SQL Server PVC for persistent data storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlserver-config
  namespace: sqlserver-namespace
  labels:
    app: sqlserver
  annotations:
    description: "SQL Server ConfigMap to store environment variables including credentials"
data:
  MSSQL_USER: "sa"
  SA_PASSWORD: "sqlpassword!123"
  ACCEPT_EULA: "Y"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
  namespace: sqlserver-namespace
  labels:
    app: sqlserver
    tier: backend
  annotations:
    description: "SQL Server deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
      annotations:
        description: "SQL Server pod"
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_USER
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: MSSQL_USER
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: SA_PASSWORD
        - name: ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: ACCEPT_EULA
        volumeMounts:
        - name: sqlserver-storage
          mountPath: /var/opt/mssql
        resources:
          requests:
            memory: "2Gi"  
            cpu: "500m"     
          limits:
            memory: "4Gi"  
            cpu: "1000m" 
      volumes:
      - name: sqlserver-storage
        persistentVolumeClaim:
          claimName: sqlserver-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  namespace: sqlserver-namespace
  labels:
    app: sqlserver
  annotations:
    description: "SQL Server ClusterIP service"
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: sqlserver

---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-nodeport-service
  namespace: sqlserver-namespace
  labels:
    app: sqlserver
  annotations:
    description: "SQL Server NodePort service for external access"
spec:
  type: NodePort
  ports:
    - port: 1433           
      targetPort: 1433        
      nodePort: 30000      
  selector:
    app: sqlserver
